// The reasons of a Recommendation ("you may like this applicant because …"), generated by code
// from the Match score breakdown, so they work without a model (ADR 0004). Templated in German
// and English.

// A subscore at least this high is a strength; one below the other is a notable weakness.
const STRENGTH = 0.75;
const WEAKNESS = 0.6;
const MAX_STRENGTHS = 3;

const LOCALES = { de: "de-DE", en: "en-GB" };

const formatNumber = (language, value) => new Intl.NumberFormat(LOCALES[language], { maximumFractionDigits: 1 }).format(value);
const formatPercent = (language, ratio) => `${formatNumber(language, ratio * 100)} %`;

// Per criterion and language, the noun phrase of a strength / a weakness of this applicant
// ({ profile, rentToIncome }); `language` formats its numbers.
const STRENGTHS = {
  affordability: {
    en: ({ rentToIncome }) => `low rent burden (${formatPercent("en", rentToIncome)} of net household income)`,
    de: ({ rentToIncome }) => `geringe Mietbelastung (${formatPercent("de", rentToIncome)} des Haushaltsnettoeinkommens)`,
  },
  schufa: { en: () => "clean SCHUFA", de: () => "saubere SCHUFA" },
  documents: { en: () => "complete documents", de: () => "vollständige Unterlagen" },
  credibility: {
    en: ({ profile }) => `high credibility (${formatNumber("en", profile.credibilityScore)}/100)`,
    de: ({ profile }) => `hohe Glaubwürdigkeit (${formatNumber("de", profile.credibilityScore)}/100)`,
  },
  employment: {
    en: ({ profile }) => (profile.employmentType === "civil_servant" ? "civil-servant status" : "permanent job"),
    de: ({ profile }) => (profile.employmentType === "civil_servant" ? "Beamtenstatus" : "unbefristete Stelle"),
  },
  previousLandlord: {
    en: () => "previous-landlord confirmation without arrears",
    de: () => "Vorvermieterbescheinigung ohne Mietrückstände",
  },
};

const SCHUFA_WEAKNESSES = {
  minor_entries: { en: "minor SCHUFA entries", de: "kleinere SCHUFA-Einträge" },
  negative: { en: "negative SCHUFA entries", de: "negative SCHUFA-Einträge" },
  missing: { en: "no usable SCHUFA-Auskunft", de: "keine verwertbare SCHUFA-Auskunft" },
};

const EMPLOYMENT_WEAKNESSES = {
  student_with_guarantor: { en: "studies with a guarantor", de: "Studium mit Bürgschaft" },
  other: { en: "no permanent employment", de: "keine feste Anstellung" },
};

// The previous-landlord confirmation's state behind a subscore below the weakness line.
function previousLandlordWeakness({ status, arrears }) {
  if (status === "not_required") return { en: "first flat, no previous landlord", de: "erste Wohnung, kein Vorvermieter" };
  if (status === "present" && arrears) return { en: "rent arrears with the previous landlord", de: "Mietrückstände beim Vorvermieter" };
  return { en: "no previous-landlord confirmation", de: "keine Vorvermieterbescheinigung" };
}

const WEAKNESSES = {
  affordability: {
    en: ({ rentToIncome }) => `rent burden of ${formatPercent("en", rentToIncome)} of net household income`,
    de: ({ rentToIncome }) => `Mietbelastung von ${formatPercent("de", rentToIncome)} des Haushaltsnettoeinkommens`,
  },
  schufa: {
    en: ({ profile }) => (SCHUFA_WEAKNESSES[profile.schufaStatus] ?? SCHUFA_WEAKNESSES.missing).en,
    de: ({ profile }) => (SCHUFA_WEAKNESSES[profile.schufaStatus] ?? SCHUFA_WEAKNESSES.missing).de,
  },
  documents: { en: () => "incomplete documents", de: () => "unvollständige Unterlagen" },
  credibility: {
    en: ({ profile }) => `low credibility (${formatNumber("en", profile.credibilityScore)}/100)`,
    de: ({ profile }) => `geringe Glaubwürdigkeit (${formatNumber("de", profile.credibilityScore)}/100)`,
  },
  employment: {
    en: ({ profile }) => (EMPLOYMENT_WEAKNESSES[profile.employmentType] ?? EMPLOYMENT_WEAKNESSES.other).en,
    de: ({ profile }) => (EMPLOYMENT_WEAKNESSES[profile.employmentType] ?? EMPLOYMENT_WEAKNESSES.other).de,
  },
  previousLandlord: {
    en: ({ profile }) => previousLandlordWeakness(profile.documentCheck.previousLandlord).en,
    de: ({ profile }) => previousLandlordWeakness(profile.documentCheck.previousLandlord).de,
  },
};

const SENTENCES = {
  en: {
    and: "and",
    because: (strengths) => `You may like this applicant for their ${strengths}.`,
    fallback: (score) => `You may like this applicant for their overall Match score of ${formatNumber("en", score)}.`,
    weakness: (weakness) => ` To note: ${weakness}.`,
  },
  de: {
    and: "und",
    because: (strengths) => `Dieser Bewerber könnte Ihnen gefallen: ${strengths}.`,
    fallback: (score) => `Dieser Bewerber könnte Ihnen gefallen: Gesamt-Match-Score von ${formatNumber("de", score)}.`,
    weakness: (weakness) => ` Zu beachten: ${weakness}.`,
  },
};

// "a", "a and b", "a, b and c".
function listOf(phrases, and) {
  if (phrases.length <= 1) return phrases.join("");
  return `${phrases.slice(0, -1).join(", ")} ${and} ${phrases.at(-1)}`;
}

// The criteria that count (weight above zero), strongest first: by subscore, then by weight,
// then in the breakdown's order.
function criteriaByStrength(breakdown) {
  const order = Object.keys(breakdown);
  return order
    .filter((criterion) => breakdown[criterion].weight > 0)
    .sort(
      (a, b) =>
        breakdown[b].subscore - breakdown[a].subscore || breakdown[b].weight - breakdown[a].weight || order.indexOf(a) - order.indexOf(b),
    );
}

// The weakest criterion below the weakness line: by subscore, then by the larger weight.
function weaknessOf(breakdown) {
  const weakest = criteriaByStrength(breakdown)
    .filter((criterion) => breakdown[criterion].subscore < WEAKNESS)
    .sort((a, b) => breakdown[a].subscore - breakdown[b].subscore || breakdown[b].weight - breakdown[a].weight);
  return weakest[0] ?? null;
}

// recommendationReasons({ profile, breakdown, rentToIncome, matchScore }) → { strengths, weakness,
// reason: { de, en } }: the two or three strongest criteria (subscore at least 0.75), the notable
// weakness (the lowest subscore below 0.6, or null), and the sentence built from them in each
// language. Without a strength, the sentence names the Match score instead.
export function recommendationReasons({ profile, breakdown, rentToIncome, matchScore }) {
  const strengths = criteriaByStrength(breakdown)
    .filter((criterion) => breakdown[criterion].subscore >= STRENGTH)
    .slice(0, MAX_STRENGTHS);
  const weakness = weaknessOf(breakdown);
  const facts = { profile, rentToIncome };
  const sentence = (language) => {
    const words = SENTENCES[language];
    const opening =
      strengths.length > 0
        ? words.because(listOf(strengths.map((criterion) => STRENGTHS[criterion][language](facts)), words.and))
        : words.fallback(matchScore);
    return weakness ? opening + words.weakness(WEAKNESSES[weakness][language](facts)) : opening;
  };
  return { strengths, weakness, reason: { de: sentence("de"), en: sentence("en") } };
}
